/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class MessageSchema extends BaseModel {
  static $columns = ['contenu', 'dateEnvoi', 'id', 'idDestinataire', 'idExpediteur', 'lu'] as const
  $columns = MessageSchema.$columns
  @column()
  declare contenu: string
  @column.dateTime()
  declare dateEnvoi: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare idDestinataire: number | null
  @column()
  declare idExpediteur: number | null
  @column()
  declare lu: boolean | null
}

export class PredictionSchema extends BaseModel {
  static $columns = ['accuracy', 'createdAt', 'filename', 'id', 'label', 'modelUsed', 'updatedAt'] as const
  $columns = PredictionSchema.$columns
  @column()
  declare accuracy: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare filename: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare label: string
  @column()
  declare modelUsed: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RoleSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'updatedAt'] as const
  $columns = RoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['address', 'avatarUrl', 'bio', 'createdAt', 'email', 'fullName', 'googleId', 'id', 'isPrivate', 'isVerified', 'password', 'phone', 'pseudo', 'tokenVerification', 'tokenVerificationExpiresAt', 'twoFactorCode', 'twoFactorExpiresAt', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare address: string | null
  @column()
  declare avatarUrl: string | null
  @column()
  declare bio: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string
  @column()
  declare googleId: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isPrivate: boolean | null
  @column()
  declare isVerified: boolean | null
  @column({ serializeAs: null })
  declare password: string | null
  @column()
  declare phone: string | null
  @column()
  declare pseudo: string | null
  @column()
  declare tokenVerification: string | null
  @column.dateTime()
  declare tokenVerificationExpiresAt: DateTime | null
  @column()
  declare twoFactorCode: string | null
  @column.dateTime()
  declare twoFactorExpiresAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
