/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class BlockSchema extends BaseModel {
  static $columns = ['id', 'idBlocker', 'idBlocked', 'createdAt'] as const
  $columns = BlockSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare idBlocker: number | null
  @column()
  declare idBlocked: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
}

export class CommentaireSchema extends BaseModel {
  static $columns = ['id', 'contenu', 'dateCommentaire', 'idUser', 'idTweet'] as const
  $columns = CommentaireSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare contenu: string
  @column.dateTime()
  declare dateCommentaire: DateTime | null
  @column()
  declare idUser: number | null
  @column()
  declare idTweet: number | null
}

export class FollowRequestSchema extends BaseModel {
  static $columns = ['id', 'followerId', 'followingId', 'status', 'createdAt', 'updatedAt'] as const
  $columns = FollowRequestSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare followerId: number | null
  @column()
  declare followingId: number | null
  @column()
  declare status: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class FollowSchema extends BaseModel {
  static $columns = ['idFollower', 'idFollowing', 'dateFollow'] as const
  $columns = FollowSchema.$columns
  @column()
  declare idFollower: number
  @column()
  declare idFollowing: number
  @column.dateTime()
  declare dateFollow: DateTime | null
}

export class HashtagSchema extends BaseModel {
  static $columns = ['id', 'name', 'createdAt'] as const
  $columns = HashtagSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
}

export class LikeSchema extends BaseModel {
  static $columns = ['id', 'idUser', 'idTweet', 'dateLike'] as const
  $columns = LikeSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare idUser: number | null
  @column()
  declare idTweet: number | null
  @column.dateTime()
  declare dateLike: DateTime | null
}

export class MediaSchema extends BaseModel {
  static $columns = ['id', 'typeMedia', 'urlMedia', 'idTweet'] as const
  $columns = MediaSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare typeMedia: string
  @column()
  declare urlMedia: string
  @column()
  declare idTweet: number | null
}

export class MessageSchema extends BaseModel {
  static $columns = ['id', 'contenu', 'dateEnvoi', 'lu', 'idExpediteur', 'idDestinataire'] as const
  $columns = MessageSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare contenu: string
  @column.dateTime()
  declare dateEnvoi: DateTime | null
  @column()
  declare lu: boolean | null
  @column()
  declare idExpediteur: number | null
  @column()
  declare idDestinataire: number | null
}

export class RetweetSchema extends BaseModel {
  static $columns = ['id', 'idUser', 'idTweet', 'contenu', 'dateRetweet'] as const
  $columns = RetweetSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare idUser: number | null
  @column()
  declare idTweet: number | null
  @column()
  declare contenu: string
  @column.dateTime()
  declare dateRetweet: DateTime | null
}

export class TweetHashtagSchema extends BaseModel {
  static $columns = ['id', 'tweetId', 'hashtagId'] as const
  $columns = TweetHashtagSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tweetId: number | null
  @column()
  declare hashtagId: number | null
}

export class TweetSchema extends BaseModel {
  static $columns = ['id', 'contenu', 'datePublication', 'idUser'] as const
  $columns = TweetSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare contenu: string
  @column.dateTime()
  declare datePublication: DateTime | null
  @column()
  declare idUser: number | null
}

export class UserSchema extends BaseModel {
  static $columns = ['id', 'fullName', 'pseudo', 'email', 'phone', 'bio', 'address', 'avatarUrl', 'password', 'isVerified', 'isPrivate', 'tokenVerification', 'tokenVerificationExpiresAt', 'twoFactorCode', 'twoFactorExpiresAt', 'createdAt', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare fullName: string
  @column()
  declare pseudo: string | null
  @column()
  declare email: string
  @column()
  declare phone: string | null
  @column()
  declare bio: string | null
  @column()
  declare address: string | null
  @column()
  declare avatarUrl: string | null
  @column({ serializeAs: null })
  declare password: string | null
  @column()
  declare isVerified: boolean | null
  @column()
  declare isPrivate: boolean | null
  @column()
  declare tokenVerification: string | null
  @column.dateTime()
  declare tokenVerificationExpiresAt: DateTime | null
  @column()
  declare twoFactorCode: string | null
  @column.dateTime()
  declare twoFactorExpiresAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
